# Generated by Django 5.1.15 on 2026-06-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('phone', models.CharField(blank=True, max_length=40, null=True)),
                ('provider', models.CharField(default='email', max_length=20)),
                ('avatar_path', models.CharField(blank=True, max_length=500, null=True)),
                ('city', models.CharField(blank=True, max_length=120, null=True)),
                ('password_hash', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
    ]
