# Generated by Django 5.1.15 on 2026-06-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='realtime_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='route_public',
            field=models.BooleanField(default=False),
        ),
    ]
