# Generated by Django 5.1.15 on 2026-06-23 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_profile_public_account_realtime_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='block_reason',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='account',
            name='is_blocked',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
