# Generated by Django 5.1.15 on 2026-06-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_block_reason_account_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='needs_review',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
