# Generated by Django 5.1.15 on 2026-06-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_needs_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='account',
            name='avatar_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='account',
            name='block_reason',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Причина блокировки'),
        ),
        migrations.AlterField(
            model_name='account',
            name='city',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.CharField(max_length=200, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_blocked',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Заблокирован'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='account',
            name='needs_review',
            field=models.BooleanField(db_index=True, default=False, verbose_name='На проверке'),
        ),
        migrations.AlterField(
            model_name='account',
            name='password_hash',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Хэш пароля'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_public',
            field=models.BooleanField(default=False, verbose_name='Профиль публичный'),
        ),
        migrations.AlterField(
            model_name='account',
            name='provider',
            field=models.CharField(default='email', max_length=20, verbose_name='Способ входа'),
        ),
        migrations.AlterField(
            model_name='account',
            name='realtime_public',
            field=models.BooleanField(default=False, verbose_name='Геопозиция в реальном времени'),
        ),
        migrations.AlterField(
            model_name='account',
            name='route_public',
            field=models.BooleanField(default=False, verbose_name='Маршруты публичны'),
        ),
    ]
