# Generated by Django 5.1.15 on 2026-06-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_options_alter_account_avatar_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='addresses',
            field=models.JSONField(blank=True, default=list, verbose_name='Адреса доставки'),
        ),
    ]
