# Generated by Django 5.2.17 on 2026-08-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='loyalty_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=6, verbose_name='Код лояльности'),
        ),
    ]
