# Generated by Django 5.2.17 on 2026-08-31 04:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OneCExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата и время')),
                ('operation', models.CharField(choices=[('catalog', 'Каталог'), ('prices', 'Цены и остатки')], db_index=True, max_length=16, verbose_name='Операция')),
                ('status', models.CharField(choices=[('ok', 'Успешно'), ('partial', 'С замечаниями'), ('error', 'Ошибка')], db_index=True, default='ok', max_length=16, verbose_name='Статус')),
                ('received', models.IntegerField(default=0, verbose_name='Получено позиций')),
                ('created_count', models.IntegerField(default=0, verbose_name='Добавлено товаров')),
                ('updated_count', models.IntegerField(default=0, verbose_name='Обновлено товаров')),
                ('skipped', models.IntegerField(default=0, verbose_name='Пропущено')),
                ('kept_by_owner', models.JSONField(blank=True, default=list, verbose_name='Оставлено за владельцем')),
                ('errors', models.JSONField(blank=True, default=list, verbose_name='Замечания')),
                ('duration_ms', models.IntegerField(default=0, verbose_name='Длительность, мс')),
                ('detail', models.CharField(blank=True, default='', max_length=200, verbose_name='Пояснение')),
            ],
            options={
                'verbose_name': 'Обмен с 1С',
                'verbose_name_plural': 'Журнал обмена с 1С',
                'ordering': ['-created_at'],
            },
        ),
    ]
