# Generated by Django 5.2.17 on 2026-09-02 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onecexchange',
            name='operation',
            field=models.CharField(choices=[('categories', 'Категории'), ('catalog', 'Каталог'), ('prices', 'Цены и остатки')], db_index=True, max_length=16, verbose_name='Операция'),
        ),
    ]
