# Generated by Django 5.2.17 on 2026-09-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_alter_onecexchange_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onecexchange',
            name='operation',
            field=models.CharField(choices=[('categories', 'Категории'), ('catalog', 'Каталог'), ('prices', 'Цены и остатки'), ('orders', 'Заказы в 1С'), ('order-status', 'Статусы из 1С')], db_index=True, max_length=16, verbose_name='Операция'),
        ),
    ]
