# Generated by Django 5.1.15 on 2026-06-18 03:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=40)),
                ('order_id', models.CharField(max_length=40)),
                ('total', models.FloatField(default=0)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('points_redeemed', models.IntegerField(default=0)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'store_orders',
                'ordering': ['-created_at'],
                'unique_together': {('user_id', 'order_id')},
            },
        ),
    ]
