# Generated by Django 5.1.15 on 2026-06-24 16:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=40, verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payload',
            field=models.JSONField(default=dict, verbose_name='Данные заказа (JSON)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='points_redeemed',
            field=models.IntegerField(default=0, verbose_name='Списано баллов'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('paid', 'Оплачен'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('cancelled', 'Отменён')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.FloatField(default=0, verbose_name='Сумма, ₽'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_id',
            field=models.CharField(db_index=True, max_length=40, verbose_name='Пользователь (ID)'),
        ),
    ]
