# Generated by Django 5.2.17 on 2026-08-24 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_payment_id_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=80, verbose_name='ID платежа'),
        ),
    ]
