# Generated by Django 5.2.17 on 2026-09-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='onec_number',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Номер документа в 1С'),
        ),
        migrations.AddField(
            model_name='order',
            name='onec_status',
            field=models.CharField(blank=True, choices=[('accepted', 'Принят в 1С'), ('assembled', 'Собран'), ('shipped', 'Отгружен'), ('delivered', 'Доставлен'), ('canceled', 'Отменён'), ('cancelled', 'Отменён')], default='', max_length=20, verbose_name='Статус в 1С'),
        ),
        migrations.AddField(
            model_name='order',
            name='onec_status_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Статус обновлён'),
        ),
        migrations.AddField(
            model_name='order',
            name='onec_taken_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Забран в 1С'),
        ),
    ]
