# Generated by Django 5.1.15 on 2026-06-18 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, default='', max_length=200)),
                ('image_url', models.CharField(blank=True, default='', max_length=300)),
                ('action', models.CharField(blank=True, default='', max_length=80)),
                ('sort', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'catalog_banners',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('emoji', models.CharField(blank=True, default='', max_length=16)),
                ('image_url', models.CharField(blank=True, max_length=300, null=True)),
                ('sort', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'catalog_categories',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, default='', max_length=120)),
                ('category_id', models.CharField(db_index=True, max_length=40)),
                ('price', models.FloatField()),
                ('old_price', models.FloatField(blank=True, null=True)),
                ('image_urls', models.JSONField(default=list)),
                ('description', models.TextField(blank=True, default='')),
                ('sizes', models.JSONField(default=list)),
                ('colors', models.JSONField(default=list)),
                ('is_new', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('rating', models.FloatField(default=0)),
                ('review_count', models.IntegerField(default=0)),
                ('in_stock', models.BooleanField(default=True)),
                ('sort', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'catalog_products',
                'ordering': ['sort'],
            },
        ),
    ]
