# Generated by Django 5.1.15 on 2026-06-28 10:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_banner_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(db_index=True, max_length=40, verbose_name='Товар (ID)')),
                ('user_id', models.CharField(db_index=True, max_length=40, verbose_name='Пользователь (ID)')),
                ('rating', models.IntegerField(verbose_name='Оценка (1–5)')),
                ('text', models.TextField(blank=True, default='', verbose_name='Текст')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'db_table': 'catalog_reviews',
                'ordering': ['-created_at'],
                'unique_together': {('product_id', 'user_id')},
            },
        ),
    ]
