# Generated by Django 5.1.15 on 2026-06-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='Скрыт (модерация)'),
        ),
        migrations.AddField(
            model_name='review',
            name='photos',
            field=models.JSONField(blank=True, default=list, verbose_name='Фото (URL)'),
        ),
    ]
