# Generated by Django 5.1.15 on 2026-07-03 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_review_hidden_review_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/banners/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/categories/', verbose_name='Фото'),
        ),
    ]
