# Generated by Django 5.1.15 on 2026-07-03 04:46

from django.db import migrations, models


def copy_sort(apps, schema_editor):
    # Инициализируем раздельный порядок текущим общим sort — витрина не меняется.
    Product = apps.get_model('catalog', 'Product')
    for p in Product.objects.all().only('id', 'sort'):
        Product.objects.filter(id=p.id).update(sort_site=p.sort, sort_app=p.sort)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_banner_image_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sort_app',
            field=models.IntegerField(default=0, verbose_name='Порядок (приложение)'),
        ),
        migrations.AddField(
            model_name='product',
            name='sort_site',
            field=models.IntegerField(default=0, verbose_name='Порядок (сайт)'),
        ),
        migrations.RunPython(copy_sort, migrations.RunPython.noop),
    ]
