# Generated by Django 5.1.15 on 2026-07-03 05:11

from django.db import migrations, models


def copy_sort(apps, schema_editor):
    Banner = apps.get_model('catalog', 'Banner')
    for b in Banner.objects.all().only('id', 'sort'):
        Banner.objects.filter(id=b.id).update(sort_site=b.sort, sort_app=b.sort)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_product_sort_app_product_sort_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='sort_app',
            field=models.IntegerField(default=0, verbose_name='Порядок (приложение)'),
        ),
        migrations.AddField(
            model_name='banner',
            name='sort_site',
            field=models.IntegerField(default=0, verbose_name='Порядок (сайт)'),
        ),
        migrations.RunPython(copy_sort, migrations.RunPython.noop),
    ]
