# Generated by Django 5.1.15 on 2026-07-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_banner_sort_app_banner_sort_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('key', models.CharField(max_length=80, primary_key=True, serialize=False, verbose_name='Ключ')),
                ('value', models.TextField(blank=True, default='', verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/site/', verbose_name='Фото')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Контент сайта',
                'verbose_name_plural': 'Контент сайта',
                'db_table': 'site_content',
            },
        ),
    ]
