# Generated by Django 5.2.17 on 2026-08-31 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_banner_image_fit_focal'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='article',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Артикул'),
        ),
        migrations.AddField(
            model_name='product',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name='ID в 1С'),
        ),
        migrations.AddField(
            model_name='product',
            name='from_1c',
            field=models.JSONField(blank=True, default=dict, verbose_name='Значения из 1С'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active_1c',
            field=models.BooleanField(db_index=True, default=True, verbose_name='В продаже (1С)'),
        ),
        migrations.AddField(
            model_name='product',
            name='overrides',
            field=models.JSONField(blank=True, default=list, verbose_name='Переопределено владельцем'),
        ),
        migrations.AddField(
            model_name='product',
            name='source_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Изменён в 1С'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Остаток, шт'),
        ),
    ]
