# Generated by Django 5.2.17 on 2026-09-02 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_product_article_product_external_id_product_from_1c_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40, verbose_name='Родительская категория (ID)'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_by_size',
            field=models.JSONField(blank=True, default=dict, verbose_name='Остаток по размерам'),
        ),
    ]
