# Generated by Django 5.1.15 on 2026-06-21 10:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('terms', 'Пользовательское соглашение'), ('privacy', 'Политика конфиденциальности'), ('pd_consent', 'Согласие на обработку ПД'), ('marketing', 'Рекламные коммуникации'), ('offer', 'Оферта (Store)'), ('loyalty', 'Правила лояльности'), ('club', 'Правила сообщества')], db_index=True, max_length=20)),
                ('version', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('is_required', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'legal_documents',
                'ordering': ['doc_type', '-created_at'],
                'unique_together': {('doc_type', 'version')},
            },
        ),
        migrations.CreateModel(
            name='UserConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=40)),
                ('accepted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(blank=True, default='', max_length=30)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consents', to='legal.legaldocument')),
            ],
            options={
                'db_table': 'user_consents',
                'ordering': ['-accepted_at'],
            },
        ),
    ]
