# Generated by Django 5.1.15 on 2026-06-24 16:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legaldocument',
            options={'ordering': ['doc_type', '-created_at'], 'verbose_name': 'Юридический документ', 'verbose_name_plural': 'Юридические документы'},
        ),
        migrations.AlterModelOptions(
            name='userconsent',
            options={'ordering': ['-accepted_at'], 'verbose_name': 'Согласие пользователя', 'verbose_name_plural': 'Согласия пользователей'},
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='body',
            field=models.TextField(blank=True, default='', verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='doc_type',
            field=models.CharField(choices=[('terms', 'Пользовательское соглашение'), ('privacy', 'Политика конфиденциальности'), ('pd_consent', 'Согласие на обработку ПД'), ('marketing', 'Рекламные коммуникации'), ('offer', 'Оферта (Store)'), ('loyalty', 'Правила лояльности'), ('club', 'Правила сообщества')], db_index=True, max_length=20, verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='is_required',
            field=models.BooleanField(default=False, verbose_name='Обязателен к принятию'),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Опубликован'),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='version',
            field=models.CharField(max_length=20, verbose_name='Версия'),
        ),
        migrations.AlterField(
            model_name='userconsent',
            name='accepted_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Принято'),
        ),
        migrations.AlterField(
            model_name='userconsent',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='userconsent',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consents', to='legal.legaldocument', verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='userconsent',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Отозвано'),
        ),
        migrations.AlterField(
            model_name='userconsent',
            name='source',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='userconsent',
            name='user_id',
            field=models.CharField(db_index=True, max_length=40, verbose_name='Пользователь (ID)'),
        ),
    ]
