# Generated by Django 5.2.17 on 2026-08-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0002_alter_legaldocument_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legaldocument',
            name='doc_type',
            field=models.CharField(choices=[('terms', 'Пользовательское соглашение'), ('privacy', 'Политика конфиденциальности'), ('pd_consent', 'Согласие на обработку ПД'), ('marketing', 'Рекламные коммуникации'), ('offer', 'Оферта (Store)'), ('loyalty', 'Правила лояльности'), ('club', 'Правила сообщества'), ('delivery', 'Доставка и получение'), ('returns', 'Возврат и обмен')], db_index=True, max_length=20, verbose_name='Тип документа'),
        ),
    ]
