# Generated by Django 5.2.17 on 2026-08-29 07:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PendingTrack',
            fields=[
                ('run_id', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Забег (ID)')),
                ('user_id', models.CharField(db_index=True, max_length=40, verbose_name='Пользователь (ID)')),
                ('points', models.JSONField(default=list, verbose_name='Точки трека')),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Получен')),
            ],
            options={
                'verbose_name': 'Трек на проверке',
                'verbose_name_plural': 'Треки на проверке',
                'db_table': 'pending_tracks',
            },
        ),
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('city', models.CharField(blank=True, default='', max_length=120, verbose_name='Город')),
                ('points', models.JSONField(default=list, verbose_name='Точки линии')),
                ('length_m', models.FloatField(default=0, verbose_name='Длина, м')),
                ('min_lat', models.FloatField(db_index=True, default=0, verbose_name='Рамка: мин. широта')),
                ('max_lat', models.FloatField(default=0, verbose_name='Рамка: макс. широта')),
                ('min_lon', models.FloatField(db_index=True, default=0, verbose_name='Рамка: мин. долгота')),
                ('max_lon', models.FloatField(default=0, verbose_name='Рамка: макс. долгота')),
                ('created_by', models.CharField(blank=True, db_index=True, default='', max_length=40, verbose_name='Создал (ID)')),
                ('is_public', models.BooleanField(default=True, verbose_name='Видна всем')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создана')),
            ],
            options={
                'verbose_name': 'Тропа',
                'verbose_name_plural': 'Тропы',
                'db_table': 'trails',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrailAttempt',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='ID')),
                ('trail_id', models.CharField(db_index=True, max_length=40, verbose_name='Тропа (ID)')),
                ('user_id', models.CharField(db_index=True, max_length=40, verbose_name='Пользователь (ID)')),
                ('run_id', models.CharField(db_index=True, max_length=40, verbose_name='Забег (ID)')),
                ('started_at', models.DateTimeField(verbose_name='Начало прохождения')),
                ('duration_s', models.IntegerField(default=0, verbose_name='Время, с')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Записана')),
            ],
            options={
                'verbose_name': 'Попытка на тропе',
                'verbose_name_plural': 'Попытки на тропах',
                'db_table': 'trail_attempts',
                'ordering': ['duration_s'],
                'unique_together': {('trail_id', 'run_id')},
            },
        ),
    ]
