# Generated by Django 5.1.15 on 2026-08-09 18:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('city', models.CharField(blank=True, db_index=True, default='', max_length=120, verbose_name='Город')),
                ('region', models.CharField(blank=True, db_index=True, default='', help_text='Напр. «Республика Татарстан», «Москва» — для показа по региону клиента', max_length=120, verbose_name='Регион')),
                ('scope', models.CharField(choices=[('federal', 'Федеральный (крупный) — показывать всем'), ('regional', 'Региональный — по региону клиента'), ('local', 'Местный — по городу клиента')], db_index=True, default='regional', help_text='federal — большие старты, видны всем; regional/local — по региону/городу клиента', max_length=10, verbose_name='Масштаб')),
                ('place', models.CharField(blank=True, default='', max_length=200, verbose_name='Место старта')),
                ('date', models.DateField(db_index=True, verbose_name='Дата старта')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Дата окончания (если многодневный)')),
                ('type', models.CharField(choices=[('road', 'Шоссе'), ('trail', 'Трейл'), ('night', 'Ночной'), ('fest', 'Фестиваль'), ('relay', 'Эстафета'), ('kids', 'Детский'), ('other', 'Другое')], db_index=True, default='road', max_length=12, verbose_name='Тип')),
                ('distances', models.JSONField(blank=True, default=list, verbose_name='Дистанции')),
                ('reg_status', models.CharField(choices=[('open', 'Регистрация открыта'), ('soon', 'Скоро'), ('closed', 'Регистрация закрыта'), ('done', 'Завершён')], default='soon', max_length=12, verbose_name='Регистрация')),
                ('reg_url', models.URLField(blank=True, default='', verbose_name='Ссылка на регистрацию')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='races/', verbose_name='Обложка (необязательно)')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Широта старта')),
                ('lng', models.FloatField(blank=True, null=True, verbose_name='Долгота старта')),
                ('points', models.IntegerField(default=0, verbose_name='Баллы за финиш')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='Опубликован')),
                ('source', models.CharField(blank=True, db_index=True, default='manual', max_length=40, verbose_name='Источник')),
                ('source_url', models.URLField(blank=True, default='', verbose_name='Ссылка на источник')),
                ('external_id', models.CharField(blank=True, db_index=True, default='', max_length=120, verbose_name='ID в источнике')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Забег (старт)',
                'verbose_name_plural': 'Забеги (старты)',
                'db_table': 'races',
                'ordering': ['date', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_id__gt', '')), fields=('source', 'external_id'), name='uniq_race_source_external')],
            },
        ),
    ]
