# Generated by Django 5.2.17 on 2026-08-30 04:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalWorkout',
            fields=[
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=40, verbose_name='Пользователь (ID)')),
                ('source', models.CharField(choices=[('healthconnect', 'Health Connect (Android)'), ('applehealth', 'Apple Health'), ('file', 'Файл GPX/TCX/FIT'), ('garmin', 'Garmin'), ('suunto', 'Suunto'), ('coros', 'COROS')], db_index=True, max_length=20, verbose_name='Источник')),
                ('source_id', models.CharField(max_length=120, verbose_name='ID у источника')),
                ('started_at', models.DateTimeField(db_index=True, verbose_name='Начало')),
                ('duration_s', models.IntegerField(default=0, verbose_name='Длительность, с')),
                ('distance_m', models.FloatField(default=0, verbose_name='Дистанция, м')),
                ('sport', models.CharField(blank=True, default='', max_length=30, verbose_name='Вид спорта')),
                ('avg_hr', models.IntegerField(blank=True, null=True, verbose_name='Средний пульс')),
                ('max_hr', models.IntegerField(blank=True, null=True, verbose_name='Максимальный пульс')),
                ('calories', models.IntegerField(blank=True, null=True, verbose_name='Калории')),
                ('run_id', models.CharField(blank=True, default='', max_length=40, verbose_name='Наш забег (ID)')),
                ('points_awarded', models.IntegerField(default=0, verbose_name='Начислено баллов')),
                ('flagged', models.BooleanField(db_index=True, default=False, verbose_name='Помечен (чит)')),
                ('flag_reason', models.CharField(blank=True, default='', max_length=200, verbose_name='Причина пометки')),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Импортирована')),
            ],
            options={
                'verbose_name': 'Тренировка извне',
                'verbose_name_plural': 'Тренировки извне',
                'db_table': 'external_workouts',
                'ordering': ['-started_at'],
                'unique_together': {('user_id', 'source', 'source_id')},
            },
        ),
    ]
