# Generated by Django 5.1.15 on 2026-07-04 05:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, db_index=True, default='', max_length=40, verbose_name='Пользователь (ID)')),
                ('name', models.CharField(db_index=True, max_length=60, verbose_name='Событие')),
                ('source', models.CharField(blank=True, default='server', max_length=20, verbose_name='Источник')),
                ('props', models.JSONField(blank=True, default=dict, verbose_name='Свойства')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'Аналитика (события)',
                'db_table': 'analytics_events',
                'indexes': [models.Index(fields=['name', 'created_at'], name='analytics_e_name_9da7eb_idx')],
            },
        ),
    ]
