# Generated by Django 5.1.15 on 2026-06-24 16:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0003_shoeasset_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoeasset',
            options={'ordering': ['-created_at'], 'verbose_name': 'Кроссовки', 'verbose_name_plural': 'Кроссовки'},
        ),
        migrations.AlterField(
            model_name='shoeasset',
            name='applied_runs',
            field=models.JSONField(default=list, verbose_name='Учтённые забеги'),
        ),
        migrations.AlterField(
            model_name='shoeasset',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Куплены'),
        ),
        migrations.AlterField(
            model_name='shoeasset',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=400, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='shoeasset',
            name='max_km',
            field=models.FloatField(default=600, verbose_name='Ресурс, км'),
        ),
        migrations.AlterField(
            model_name='shoeasset',
            name='model',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='shoeasset',
            name='order_id',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Заказ (ID)'),
        ),
        migrations.AlterField(
            model_name='shoeasset',
            name='product_id',
            field=models.CharField(max_length=40, verbose_name='Товар (ID)'),
        ),
        migrations.AlterField(
            model_name='shoeasset',
            name='retired',
            field=models.BooleanField(default=False, verbose_name='Списаны'),
        ),
        migrations.AlterField(
            model_name='shoeasset',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('active', 'Активные'), ('declined', 'Отклонены')], db_index=True, default='pending', max_length=12, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='shoeasset',
            name='total_km',
            field=models.FloatField(default=0, verbose_name='Пробег, км'),
        ),
        migrations.AlterField(
            model_name='shoeasset',
            name='user_id',
            field=models.CharField(db_index=True, max_length=40, verbose_name='Пользователь (ID)'),
        ),
    ]
