# Generated by Django 5.1.15 on 2026-06-15 14:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('logo', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner_id', models.CharField(max_length=40)),
                ('join_policy', models.CharField(default='open', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'clubs',
            },
        ),
        migrations.CreateModel(
            name='ClubJoinRequest',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('club_id', models.CharField(db_index=True, max_length=40)),
                ('user_id', models.CharField(max_length=40)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'club_join_requests',
            },
        ),
        migrations.CreateModel(
            name='ClubMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.CharField(db_index=True, max_length=40)),
                ('user_id', models.CharField(max_length=40, unique=True)),
                ('role', models.CharField(default='member', max_length=20)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'club_members',
                'unique_together': {('club_id', 'user_id')},
            },
        ),
    ]
