# Generated by Django 5.1.15 on 2026-06-23 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='is_hidden',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
