# Generated by Django 5.1.15 on 2026-06-24 16:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_club_is_hidden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'verbose_name': 'Клуб', 'verbose_name_plural': 'Клубы'},
        ),
        migrations.AlterModelOptions(
            name='clubjoinrequest',
            options={'verbose_name': 'Заявка в клуб', 'verbose_name_plural': 'Заявки в клуб'},
        ),
        migrations.AlterModelOptions(
            name='clubmember',
            options={'verbose_name': 'Участник клуба', 'verbose_name_plural': 'Участники клубов'},
        ),
        migrations.AlterField(
            model_name='club',
            name='city',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='club',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='club',
            name='id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='club',
            name='is_hidden',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Скрыт (модерация)'),
        ),
        migrations.AlterField(
            model_name='club',
            name='join_policy',
            field=models.CharField(choices=[('open', 'Открытый'), ('request', 'По заявке')], default='open', max_length=20, verbose_name='Приём в клуб'),
        ),
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='club',
            name='owner_id',
            field=models.CharField(max_length=40, verbose_name='Владелец (ID)'),
        ),
        migrations.AlterField(
            model_name='clubjoinrequest',
            name='club_id',
            field=models.CharField(db_index=True, max_length=40, verbose_name='Клуб (ID)'),
        ),
        migrations.AlterField(
            model_name='clubjoinrequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='clubjoinrequest',
            name='id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='clubjoinrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='clubjoinrequest',
            name='user_id',
            field=models.CharField(max_length=40, verbose_name='Пользователь (ID)'),
        ),
        migrations.AlterField(
            model_name='clubmember',
            name='club_id',
            field=models.CharField(db_index=True, max_length=40, verbose_name='Клуб (ID)'),
        ),
        migrations.AlterField(
            model_name='clubmember',
            name='joined_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Вступил'),
        ),
        migrations.AlterField(
            model_name='clubmember',
            name='role',
            field=models.CharField(choices=[('owner', 'Владелец'), ('member', 'Участник')], default='member', max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='clubmember',
            name='user_id',
            field=models.CharField(max_length=40, unique=True, verbose_name='Пользователь (ID)'),
        ),
    ]
