# Generated by Django 5.1.15 on 2026-06-27 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_alter_club_options_alter_clubjoinrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='style',
            field=models.CharField(default='minimal', max_length=20, verbose_name='Стиль оформления'),
        ),
    ]
