# Generated by Django 5.1.15 on 2026-06-27 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_club_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='cover',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Обложка'),
        ),
    ]
