# Generated by Django 5.1.15 on 2026-06-27 11:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_club_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubChallenge',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.CharField(db_index=True, max_length=40, verbose_name='Клуб (ID)')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('target_km', models.FloatField(verbose_name='Цель (км)')),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Старт')),
                ('end_at', models.DateTimeField(verbose_name='Финиш')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Челлендж клуба',
                'verbose_name_plural': 'Челленджи клубов',
                'db_table': 'club_challenges',
            },
        ),
    ]
