# Generated by Django 5.2.17 on 2026-08-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='runnerprofile',
            name='trails_enabled',
            field=models.BooleanField(default=True, verbose_name='Участвовать в тропах'),
        ),
    ]
