# Generated by Django 5.2.17 on 2026-08-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_runnerprofile_trails_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='runnerprofile',
            name='focus',
            field=models.CharField(blank=True, choices=[('health', 'Для здоровья'), ('compete', 'Соревноваться'), ('social', 'С людьми'), ('calm', 'Разгрузить голову')], default='', max_length=10, verbose_name='Зачем бегает'),
        ),
    ]
