# Generated by Django 5.2.17 on 2026-08-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_runnerprofile_focus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runnerprofile',
            name='focus',
            field=models.CharField(blank=True, choices=[('health', 'Для здоровья'), ('compete', 'Соревноваться'), ('social', 'С людьми'), ('calm', 'Разгрузить голову'), ('skip', 'Пропустил вопрос')], default='', max_length=10, verbose_name='Зачем бегает'),
        ),
    ]
