# Generated by Django 5.2.17 on 2026-08-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_alter_runnerprofile_focus'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonClose',
            fields=[
                ('month', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Закрытие сезона',
                'verbose_name_plural': 'Закрытия сезонов',
                'db_table': 'league_season_closes',
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('tier', models.IntegerField(verbose_name='Уровень (0=Асфальт … 6=Лайм)')),
                ('week_start', models.DateField(db_index=True, verbose_name='Понедельник недели')),
                ('seq', models.IntegerField(default=1, verbose_name='Номер группы в уровне')),
                ('closed', models.BooleanField(default=False, verbose_name='Неделя закрыта')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Дивизион недели',
                'verbose_name_plural': 'Дивизионы недели',
                'db_table': 'league_divisions',
                'unique_together': {('tier', 'week_start', 'seq')},
            },
        ),
        migrations.CreateModel(
            name='DivisionMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_id', models.CharField(db_index=True, max_length=40)),
                ('user_id', models.CharField(db_index=True, max_length=40)),
                ('week_start', models.DateField()),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Участник дивизиона',
                'verbose_name_plural': 'Участники дивизионов',
                'db_table': 'league_division_members',
                'unique_together': {('user_id', 'week_start')},
            },
        ),
        migrations.CreateModel(
            name='SeasonResult',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('month', models.CharField(db_index=True, max_length=7)),
                ('user_id', models.CharField(db_index=True, max_length=40)),
                ('place', models.IntegerField()),
                ('of', models.IntegerField()),
                ('km', models.FloatField()),
                ('runs', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Итог сезона',
                'verbose_name_plural': 'Итоги сезонов',
                'db_table': 'league_season_results',
                'unique_together': {('month', 'user_id')},
            },
        ),
    ]
