# Generated by Django 5.1.15 on 2026-06-21 18:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=40)),
                ('distance_m', models.FloatField(default=0)),
                ('duration_s', models.IntegerField(default=0)),
                ('captured_territory', models.BooleanField(default=False)),
                ('captured_zones', models.IntegerField(default=0)),
                ('finished_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'runs',
                'ordering': ['-finished_at'],
            },
        ),
    ]
