# Generated by Django 5.1.15 on 2026-06-23 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='flag_reason',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='run',
            name='flagged',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='run',
            name='points_awarded',
            field=models.IntegerField(default=0),
        ),
    ]
