# Generated by Django 5.1.15 on 2026-06-24 16:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0002_run_flag_reason_run_flagged_run_points_awarded'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='run',
            options={'ordering': ['-finished_at'], 'verbose_name': 'Пробежка', 'verbose_name_plural': 'Пробежки'},
        ),
        migrations.AlterField(
            model_name='run',
            name='captured_territory',
            field=models.BooleanField(default=False, verbose_name='Захват территории'),
        ),
        migrations.AlterField(
            model_name='run',
            name='captured_zones',
            field=models.IntegerField(default=0, verbose_name='Захвачено зон'),
        ),
        migrations.AlterField(
            model_name='run',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Загружен'),
        ),
        migrations.AlterField(
            model_name='run',
            name='distance_m',
            field=models.FloatField(default=0, verbose_name='Дистанция, м'),
        ),
        migrations.AlterField(
            model_name='run',
            name='duration_s',
            field=models.IntegerField(default=0, verbose_name='Длительность, с'),
        ),
        migrations.AlterField(
            model_name='run',
            name='finished_at',
            field=models.DateTimeField(verbose_name='Завершён'),
        ),
        migrations.AlterField(
            model_name='run',
            name='flag_reason',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Причина пометки'),
        ),
        migrations.AlterField(
            model_name='run',
            name='flagged',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Помечен (чит)'),
        ),
        migrations.AlterField(
            model_name='run',
            name='id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='run',
            name='points_awarded',
            field=models.IntegerField(default=0, verbose_name='Начислено баллов'),
        ),
        migrations.AlterField(
            model_name='run',
            name='user_id',
            field=models.CharField(db_index=True, max_length=40, verbose_name='Пользователь (ID)'),
        ),
    ]
