# Generated by Django 5.1.15 on 2026-06-15 13:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=40)),
                ('amount', models.IntegerField()),
                ('source', models.CharField(max_length=40)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('order_id', models.CharField(blank=True, max_length=40, null=True)),
                ('run_id', models.CharField(blank=True, max_length=80, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'loyalty_transactions',
            },
        ),
    ]
