# Generated by Django 5.1.15 on 2026-06-24 16:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loyaltytransaction',
            options={'verbose_name': 'Транзакция баллов', 'verbose_name_plural': 'Баллы (транзакции)'},
        ),
        migrations.AlterField(
            model_name='loyaltytransaction',
            name='amount',
            field=models.IntegerField(verbose_name='Сумма баллов'),
        ),
        migrations.AlterField(
            model_name='loyaltytransaction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='loyaltytransaction',
            name='description',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='loyaltytransaction',
            name='id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='loyaltytransaction',
            name='order_id',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Заказ (ID)'),
        ),
        migrations.AlterField(
            model_name='loyaltytransaction',
            name='run_id',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Забег (ID)'),
        ),
        migrations.AlterField(
            model_name='loyaltytransaction',
            name='source',
            field=models.CharField(max_length=40, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='loyaltytransaction',
            name='user_id',
            field=models.CharField(db_index=True, max_length=40, verbose_name='Пользователь (ID)'),
        ),
    ]
