# Generated by Django 5.2.17 on 2026-09-01 09:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Когда')),
                ('actor_name', models.CharField(blank=True, default='', max_length=150)),
                ('target_name', models.CharField(blank=True, default='', max_length=150)),
                ('action', models.CharField(max_length=160, verbose_name='Что сделано')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто')),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кому')),
            ],
            options={
                'verbose_name': 'Запись журнала доступов',
                'verbose_name_plural': 'Журнал доступов',
                'ordering': ['-at'],
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='Имя')),
                ('position', models.CharField(blank=True, default='', max_length=120, verbose_name='Должность или зона ответственности')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Заведён')),
                ('invite_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('invite_expires', models.DateTimeField(blank=True, null=True, verbose_name='Ссылка действует до')),
                ('invite_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Приглашение принято')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем заведён')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='Учётная запись')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='TabPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab', models.CharField(max_length=48, verbose_name='Вкладка')),
                ('level', models.CharField(choices=[('none', 'Нет доступа'), ('view', 'Смотреть'), ('edit', 'Редактировать'), ('full', 'Редактировать и удалять')], default='view', max_length=8, verbose_name='Уровень')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tab_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Доступ к вкладке',
                'verbose_name_plural': 'Доступы к вкладкам',
                'unique_together': {('user', 'tab')},
            },
        ),
    ]
