# Generated by Django 5.1.15 on 2026-06-24 16:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='body',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='order_id',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Заказ (ID)'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='read',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('system', 'Системное'), ('order', 'Заказ'), ('promo', 'Акция')], default='system', max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user_id',
            field=models.CharField(db_index=True, max_length=40, verbose_name='Пользователь (ID)'),
        ),
    ]
