# Generated by Django 5.1.15 on 2026-06-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_devicetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('system', 'Системное'), ('order', 'Заказ'), ('promo', 'Акция'), ('level', 'Новый уровень'), ('club', 'Клуб')], default='system', max_length=20, verbose_name='Тип'),
        ),
    ]
