# Generated by Django 5.2.17 on 2026-09-02 03:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=255, verbose_name='Токен устройства')),
                ('user_id', models.CharField(db_index=True, max_length=40, verbose_name='Пользователь (ID)')),
                ('platform', models.CharField(default='android', max_length=20, verbose_name='Платформа')),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Впервые')),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последний раз')),
            ],
            options={
                'verbose_name': 'Устройство и аккаунт',
                'verbose_name_plural': 'Устройства и аккаунты',
                'db_table': 'device_accounts',
                'unique_together': {('token', 'user_id')},
            },
        ),
    ]
